# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curspace < Formula
  desc "Terminal-first project discovery and workspace launcher for Cursor IDE"
  homepage "https://github.com/frknikiz/curspace"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frknikiz/curspace/releases/download/v1.5.0/curspace_1.5.0_darwin_amd64.tar.gz"
      sha256 "5b4f6cc00f5efd10fae5edf66803d9c3f561cdedfbe0bf90937e8886c5086e99"

      define_method(:install) do
        bin.install "curspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frknikiz/curspace/releases/download/v1.5.0/curspace_1.5.0_darwin_arm64.tar.gz"
      sha256 "54eff8e9a43240ff2c7d054a1627233f527759c08758d395bbe7b336bdbc987d"

      define_method(:install) do
        bin.install "curspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frknikiz/curspace/releases/download/v1.5.0/curspace_1.5.0_linux_amd64.tar.gz"
      sha256 "dc72e5e277b2b7ba7a785be589467c9121e34e731ef5cd0ce86734aa11efa9ac"
      define_method(:install) do
        bin.install "curspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frknikiz/curspace/releases/download/v1.5.0/curspace_1.5.0_linux_arm64.tar.gz"
      sha256 "06adc2a927685fbf227065963dc918a368a7a5d748dd327393227e184ea16bd2"
      define_method(:install) do
        bin.install "curspace"
      end
    end
  end
end
