# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curspace < Formula
  desc "Terminal-first project discovery and workspace launcher for Cursor IDE"
  homepage "https://github.com/frknikiz/curspace"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frknikiz/curspace/releases/download/v1.2.1/curspace_1.2.1_darwin_amd64.tar.gz"
      sha256 "c37b7e56148183046f5239a01e9db9bab335257bfbde57e0b82d492dd43c9f08"

      define_method(:install) do
        bin.install "curspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frknikiz/curspace/releases/download/v1.2.1/curspace_1.2.1_darwin_arm64.tar.gz"
      sha256 "9de98cdd380b950084b5ee8d309f2dda4d3b0a7afc7bdf52b13314b067a29f82"

      define_method(:install) do
        bin.install "curspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frknikiz/curspace/releases/download/v1.2.1/curspace_1.2.1_linux_amd64.tar.gz"
      sha256 "849c5f57796c9f822de6b650e01a0fe529e676b6d5e62c4302c501e15d336d5f"
      define_method(:install) do
        bin.install "curspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frknikiz/curspace/releases/download/v1.2.1/curspace_1.2.1_linux_arm64.tar.gz"
      sha256 "3d7725444e4c199e4643ed93c2cc3f07e6eabdb7ba0995979e766d16480f3376"
      define_method(:install) do
        bin.install "curspace"
      end
    end
  end
end
